/* -*- c++ -*- */
/*
 * Copyright 2004,2010 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <limits.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <errno.h>
#include <sys/types.h>
#include <signal.h>

#include <iostream>
#include <pipe_source.h>
#include <gr_io_signature.h>

/*
 * Create a new instance of pipe_source and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
pipe_source_sptr 
pipe_make_source (size_t out_item_sz,
                  const char *cmd)
{
  return gnuradio::get_initial_sptr(new pipe_source (out_item_sz,
                                                     cmd));
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.
 */
static const int MIN_IN = 0;	// mininum number of input streams
static const int MAX_IN = 0;	// maximum number of input streams
static const int MIN_OUT = 1;	// minimum number of output streams
static const int MAX_OUT = 1;	// maximum number of output streams

/*
 * The private constructor
 */

pipe_source::pipe_source (size_t out_item_sz,
                          const char *cmd)
  : gr_sync_block ("pipe_source",
                   gr_make_io_signature (MIN_IN,  MAX_IN,  0),
                   gr_make_io_signature (MIN_OUT, MAX_OUT, out_item_sz)),
    d_out_item_sz (out_item_sz)
{
  create_command_process(cmd);
}


/*
 * Our virtual destructor.
 */
pipe_source::~pipe_source ()
{
  long ret;
  int pstat;

  fclose(d_cmd_stdout);

  //kill(d_cmd_pid, SIGTERM);

  do {
    ret = waitpid(d_cmd_pid, &pstat, 0);
  } while (ret == -1 && errno == EINTR);

  if (ret == -1) {
    perror("waitpid()");
    return ;
  }

  if (WIFEXITED(pstat))
    std::cerr << "Process exited with code " << WEXITSTATUS(pstat) << std::endl;
  else if (WIFSIGNALED(pstat))
    std::cerr << "Process exited with signal " << WTERMSIG(pstat) << std::endl;
  else
    std::cerr << "Abnormal process termination" << std::endl;
}


void
pipe_source::create_pipe(int pipefd[2])
{
  int ret;

  ret = pipe(pipefd);
  if (ret != 0) {
    perror("pipe()");
    throw std::runtime_error("pipe() error");
  }
}

void
pipe_source::create_command_process(const char *cmd)
{
  create_pipe(d_cmd_stdout_pipe);

  d_cmd_pid = fork();
  if (d_cmd_pid == -1) {
    perror("fork()");
    return ;
  }
  else if (d_cmd_pid == 0) {
    dup2(d_cmd_stdout_pipe[1], STDOUT_FILENO);
    close(d_cmd_stdout_pipe[1]);
    close(d_cmd_stdout_pipe[0]);

    execl("/bin/sh", "sh", "-c", cmd, NULL);

    perror("execl()");
    exit(EXIT_FAILURE);
  }
  else {
    close(d_cmd_stdout_pipe[1]);

    fcntl(d_cmd_stdout_pipe[0], F_SETFD, FD_CLOEXEC);

    d_cmd_stdout = fdopen(d_cmd_stdout_pipe[0], "r");
    if (d_cmd_stdout == NULL) {
      perror("fdopen()");
      throw std::runtime_error("fdopen() error");
      return ;
    }
  }
}


int
pipe_source::read_process_output(uint8_t *out, int nitems)
{
  size_t ret;

  ret = fread(out, d_out_item_sz, nitems, d_cmd_stdout);
  if (    ret == 0
       && ferror(d_cmd_stdout)
       && errno != EAGAIN
       && errno != EWOULDBLOCK) {
    throw std::runtime_error("fread() error");
    return (-1);
  }

  return (ret);
}


int 
pipe_source::work (int noutput_items,
                   gr_vector_const_void_star &input_items,
                   gr_vector_void_star &output_items)
{
  uint8_t *out = (uint8_t *) output_items[0];
  int n_produced;

  n_produced = read_process_output(out, noutput_items);

  return (n_produced);
}
